//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace x360_Account_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("x360_Account_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account file saved to: .
        /// </summary>
        internal static string AccountFileSaved {
            get {
                return ResourceManager.GetString("AccountFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching of account type Done! waiting for further instructions....
        /// </summary>
        internal static string AccTypePatchDone {
            get {
                return ResourceManager.GetString("AccTypePatchDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Generated a new XUID for you, the new ID is: .
        /// </summary>
        internal static string AutoGenXUID {
            get {
                return ResourceManager.GetString("AutoGenXUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Your XUID must start with &quot;0009&quot; to be valid!.
        /// </summary>
        internal static string BadXUID {
            get {
                return ResourceManager.GetString("BadXUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting current account information Done! Waiting for further instructions....
        /// </summary>
        internal static string CurrentInfoDone {
            get {
                return ResourceManager.GetString("CurrentInfoDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption was successful with devkit key!.
        /// </summary>
        internal static string DecryptedWithDevkitKey {
            get {
                return ResourceManager.GetString("DecryptedWithDevkitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decryption was successful with retail key!.
        /// </summary>
        internal static string DecryptedWithRetailKey {
            get {
                return ResourceManager.GetString("DecryptedWithRetailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0009000000.
        /// </summary>
        internal static string DefaultXUIDStart {
            get {
                return ResourceManager.GetString("DefaultXUIDStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devkit.
        /// </summary>
        internal static string Devkit {
            get {
                return ResourceManager.GetString("Devkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done patching account as offline! waiting for further instructions....
        /// </summary>
        internal static string DoneMakingOffline {
            get {
                return ResourceManager.GetString("DoneMakingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting account....
        /// </summary>
        internal static string EncryptingAccount {
            get {
                return ResourceManager.GetString("EncryptingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption complete! Waiting for further instructions....
        /// </summary>
        internal static string EncryptionComplete {
            get {
                return ResourceManager.GetString("EncryptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Your account is etheir corrupt or not decrypted, decrypt it first!.
        /// </summary>
        internal static string ErrorCorruptOrEncrypted {
            get {
                return ResourceManager.GetString("ErrorCorruptOrEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit without saving?.
        /// </summary>
        internal static string ExitWithoutSaving {
            get {
                return ResourceManager.GetString("ExitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving?.
        /// </summary>
        internal static string ExitWithoutSavingTitle {
            get {
                return ResourceManager.GetString("ExitWithoutSavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Gold.
        /// </summary>
        internal static string FamilyGold {
            get {
                return ResourceManager.GetString("FamilyGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account file loaded!.
        /// </summary>
        internal static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new XUID....
        /// </summary>
        internal static string GeneratingXUID {
            get {
                return ResourceManager.GetString("GeneratingXUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting current account information....
        /// </summary>
        internal static string GettingCurrentInfo {
            get {
                return ResourceManager.GetString("GettingCurrentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading account file into memory....
        /// </summary>
        internal static string LoadingAccFileToMemory {
            get {
                return ResourceManager.GetString("LoadingAccFileToMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done patching account as online! waiting for further instructions....
        /// </summary>
        internal static string MakeOnlineDone {
            get {
                return ResourceManager.GetString("MakeOnlineDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching account as offline....
        /// </summary>
        internal static string MakingOffline {
            get {
                return ResourceManager.GetString("MakingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching account as online....
        /// </summary>
        internal static string MakingOnline {
            get {
                return ResourceManager.GetString("MakingOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ID Generated.
        /// </summary>
        internal static string NewIDGeneratedTitle {
            get {
                return ResourceManager.GetString("NewIDGeneratedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passcode removed! Waiting for further instructions....
        /// </summary>
        internal static string PassCodeRemoved {
            get {
                return ResourceManager.GetString("PassCodeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Protected.
        /// </summary>
        internal static string PassProtected {
            get {
                return ResourceManager.GetString("PassProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathching account name....
        /// </summary>
        internal static string PatchingAccName {
            get {
                return ResourceManager.GetString("PatchingAccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching of account name done! Waiting for further instructions....
        /// </summary>
        internal static string PatchingAccNameDone {
            get {
                return ResourceManager.GetString("PatchingAccNameDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching account type....
        /// </summary>
        internal static string PatchingAccType {
            get {
                return ResourceManager.GetString("PatchingAccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching LIVE signature....
        /// </summary>
        internal static string PatchingLiveSignature {
            get {
                return ResourceManager.GetString("PatchingLiveSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching of LIVE signature Done! waiting for further instructions....
        /// </summary>
        internal static string PatchingLiveSignatureDone {
            get {
                return ResourceManager.GetString("PatchingLiveSignatureDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching XUID....
        /// </summary>
        internal static string PatchingXUID {
            get {
                return ResourceManager.GetString("PatchingXUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing passcode from account and setting it to online only....
        /// </summary>
        internal static string RemovingPasscode {
            get {
                return ResourceManager.GetString("RemovingPasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail profile?.
        /// </summary>
        internal static string RetailProfileTitle {
            get {
                return ResourceManager.GetString("RetailProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new account file....
        /// </summary>
        internal static string SavingAccountFile {
            get {
                return ResourceManager.GetString("SavingAccountFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to decrypt your account using devkit key....
        /// </summary>
        internal static string TryingDevkitKey {
            get {
                return ResourceManager.GetString("TryingDevkitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to decrypt your account using retail key....
        /// </summary>
        internal static string TryingRetailKey {
            get {
                return ResourceManager.GetString("TryingRetailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to decrypt your account!.
        /// </summary>
        internal static string UnableToDecrypt {
            get {
                return ResourceManager.GetString("UnableToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine which key to use, is this account for a retail console?.
        /// </summary>
        internal static string UnableToDetermineAccType {
            get {
                return ResourceManager.GetString("UnableToDetermineAccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New XUID successfully generated!.
        /// </summary>
        internal static string XUIDGenDone {
            get {
                return ResourceManager.GetString("XUIDGenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching XUID Done!.
        /// </summary>
        internal static string XUIDPatchDone {
            get {
                return ResourceManager.GetString("XUIDPatchDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passcode is....
        /// </summary>
        internal static string YourPasscodeIsTitle {
            get {
                return ResourceManager.GetString("YourPasscodeIsTitle", resourceCulture);
            }
        }
    }
}
