//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwizzContact.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwizzContact.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Are_you_sure_title {
            get {
                return ResourceManager.GetString("Are_you_sure_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Autoload.
        /// </summary>
        internal static string disableautoload {
            get {
                return ResourceManager.GetString("disableautoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autoload.
        /// </summary>
        internal static string enableautoload {
            get {
                return ResourceManager.GetString("enableautoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0}\Contacts.sdf.
        /// </summary>
        internal static string SQLConnect {
            get {
                return ResourceManager.GetString("SQLConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Contacts (Name,Email,Adress, ZipCode, Country, Area,Office,Mobile,Home,Company,Other) VALUES(&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;,&apos;{6}&apos;,&apos;{7}&apos;,&apos;{8}&apos;,&apos;{9}&apos;,&apos;{10}&apos;).
        /// </summary>
        internal static string SQLInsert {
            get {
                return ResourceManager.GetString("SQLInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Contacts SET Name=&apos;{0}&apos;, Email=&apos;{1}&apos;, Adress=&apos;{2}&apos;, ZipCode=&apos;{3}&apos;, Country=&apos;{4}&apos;, Area=&apos;{5}&apos;, Office=&apos;{6}&apos; , Mobile=&apos;{7}&apos;, Home=&apos;{8}&apos;, Company=&apos;{9}&apos;, Other=&apos;{10}&apos; WHERE ID=&apos;{11}&apos;.
        /// </summary>
        internal static string SQLUpdate {
            get {
                return ResourceManager.GetString("SQLUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected entry from the database?.
        /// </summary>
        internal static string Warning_Delete_entry {
            get {
                return ResourceManager.GetString("Warning_Delete_entry", resourceCulture);
            }
        }
    }
}
